### ISSUE TITLE
Supplementary paper in SIGKDD2024

### ISSUE THREAD

**Issue by SiweiPro** [SpaceLearner/Awesome-DynamicGraphLearning#3]
Hi,

A new paper based on temporal graph modeling has been published in SIGKDD 2024: "Towards Adaptive Neighborhood for Advancing Temporal Interaction Graph Modeling."

If possible, please add it. Thank you!

**Comment by SpaceLearner** [comment]
Sure, thanks for your remind, your paper has been added.

**Comment by SiweiPro** [comment]
Thank you again for your efforts!
