### ISSUE TITLE
New papers

### ISSUE THREAD

**Issue by gravins** [SpaceLearner/Awesome-DynamicGraphLearning#4]
Hi,
I hope these new papers may be of interest to you.

**SURVEY:** 
- Deep learning for dynamic graphs: models and benchmarks, accepted at IEEE Transactions on Neural Networks and Learning Systems
**url**: https://ieeexplore.ieee.org/document/10490120
**code**: https://github.com/gravins/dynamic_graph_benchmark

**PAPERS:** 
- _Long Range Propagation on Continuous-Time Dynamic Graphs_, accepted at ICML 24
**url**: https://proceedings.mlr.press/v235/gravina24a.html
**code**: https://github.com/gravins/non-dissipative-propagation-CTDGs

- _Temporal Graph ODEs for Irregularly-Sampled Time Series_, accepted at IJCAI 24
**url**: https://www.ijcai.org/proceedings/2024/445
**code**: https://github.com/gravins/TG-ODE

- _Hidden Markov Models for Temporal Graph Representation Learning_, accepted at ESANN 23
**url**: https://www.esann.org/sites/default/files/proceedings/2023/ES2023-35.pdf
**code**: https://github.com/nec-research/hidden_markov_model_temporal_graphs

- _Anomaly Detection in Continuous-Time Temporal Provenance Graphs_, accepted at Temporal Graph Learning Workshop @ NeurIPS 2023
**url**: https://openreview.net/pdf?id=88tGIxxhsfn
**code**: https://github.com/JakubReha/ProvCTDG

If possible, please add them. Thank you!

**Comment by SpaceLearner** [comment]
All the papers have been added, thank you for your help.
