### ISSUE TITLE
New papers

### ISSUE THREAD

**Issue by wondergo2017** [SpaceLearner/Awesome-DynamicGraphLearning#5]
Hi,
I hope these new papers may be of interest to you.

PAPERS:
- LLM4DyG: Can Large Language Models Solve Spatial-Temporal Problems on Dynamic Graphs? @KDD24
  - url: https://arxiv.org/abs/2310.17110
  - code: https://github.com/wondergo2017/LLM4DyG

- Spectral Invariant Learning for Dynamic Graphs under Distribution Shifts @ NeurIPS23
  - url: https://arxiv.org/abs/2403.05026
  - code: https://github.com/wondergo2017/sild

- Dynamic Graph Neural Networks Under Spatio-Temporal Distribution Shift @ NeurIPS22
  - url: https://proceedings.neurips.cc/paper_files/paper/2022/hash/2857242c9e97de339ce642e75b15ff24-Abstract-Conference.html
  - code: https://github.com/wondergo2017/DIDA

- Dynamic Heterogeneous Graph Attention Neural Architecture Search @ AAAI23
  - url: https://ojs.aaai.org/index.php/AAAI/article/view/26338
  - code: https://github.com/wondergo2017/DHGAS

If possible, please add them. Thank you!

**Comment by SpaceLearner** [comment]
All the papers have been added, thanks for your help.
